name: Deploy Backend to Production

on:
  push:
    branches:
      - dont-deploy
    paths:
      - 'apps/api/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/backend-deploy.yml'
      - 'Docker/Dockerfile.api'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile.api
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/simcasino-api:latest
            ${{ secrets.DOCKER_USERNAME }}/simcasino-api:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/simcasino-api:latest

            # Stop and remove the old container
            docker stop simcasino-api || true
            docker rm simcasino-api || true

            # Run the new container
            docker run -d \
              --name simcasino-api \
              --restart always \
              -p 5000:5000 \
              -e NODE_ENV=production \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e COOKIE_SECRET="${{ secrets.COOKIE_SECRET }}" \
              -e CORS_ORIGIN="${{ secrets.CORS_ORIGIN }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e CLIENT_URL="${{ secrets.CLIENT_URL }}" \
              -e REDIRECT_URL="${{ secrets.REDIRECT_URL }}" \
              ${{ secrets.DOCKER_USERNAME }}/simcasino-api:latest

      - name: Deployment Notification
        if: success()
        run: |
          echo "Backend successfully deployed to production."
          echo "Commit: ${GITHUB_SHA::7}"
          echo "Branch: ${GITHUB_REF#refs/heads/}"
